### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by numist** [numist/is31io7326_key_scanner#5]
The repo should have a LICENSE file.

+CC @keyboardio / @swenson / @obra: The upstream repository doesn't have an obvious license; what licenses are acceptable? I usually prefer something MIT-style.

**Comment by obra** [comment]
MIT is just great. @swenson did the early code as work for hire for Keyboardio, so, for my sins, I get to speak authoritatively on licensing for the existing code ;)

TY

**Comment by swenson** [comment]
+1 for MIT-style
